apiVersion: v2
name: safellm-oss
description: SafeLLM OSS - AI Security Gateway for Apache APISIX
type: application
version: 2.2.0
appVersion: "2.2.0"

keywords:
  - llm
  - security
  - apisix
  - pii
  - prompt-injection

home: https://github.com/safellmio/safellm-apisix-gateway-sidecar
sources:
  - https://github.com/safellmio/safellm-apisix-gateway-sidecar

maintainers:
  - name: SafeLLM Team
    url: https://safellm.io

dependencies:
  - name: redis
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
