#!/usr/bin/env python3
"""Export OSS requirements from pyproject.toml to sidecar/requirements.txt."""
from __future__ import annotations

from pathlib import Path
import tomllib


ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = ROOT / "pyproject.toml"
OUT_FILE = ROOT / "sidecar" / "requirements.txt"


def main() -> None:
    data = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    deps = data.get("project", {}).get("dependencies", [])
    header = [
        "# AUTOGENERATED from pyproject.toml (OSS base deps only).",
        "# Edit pyproject.toml and re-run scripts/export_requirements.py",
        "",
    ]
    OUT_FILE.write_text("\n".join(header + deps) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
